### ISSUE TITLE
Feature request: handle namespace label selector

### ISSUE THREAD

**Issue by matskiv** [loft-sh/vcluster-generic-crd-sync-plugin#15]
There are some CRDs that have a resource label select and namespace selector present. We would be able to support some of these by rewriting the label selectors to include namespace label selectors. This would be similar to what we do with NetworkPolicies in vcluster.

Currently, the namespace labels are added only to Pods, and this should be documented together with the new feature. The full potential of this will be realized once vcluster supports adding namespace labels to the arbitrary synced resources(FR: [https://github.com/loft-sh/vcluster/issues/748](https://github.com/loft-sh/vcluster/issues/748)) and this plugin does that as well (FR: [https://github.com/loft-sh/vcluster-generic-crd-sync-plugin/issues/14](https://github.com/loft-sh/vcluster-generic-crd-sync-plugin/issues/14))

Proposed config change - add the namespaceLabelSelectorPath for the rewriteLabelSelector/rewriteLabelExpressionsSelector patch types :

```
mappings:
  - fromVirtualCluster:
      patches:
        - op: rewriteLabelSelector
          path: .spec.labels
          namespaceLabelSelectorPath: .spec.namespaceLabels
        - op: rewriteLabelExpressionsSelector
          path: .spec.selector
          namespaceLabelSelectorPath: .spec.namespaceSelector
```
