### ISSUE TITLE
Feature request: support syncing labels without rewrite

### ISSUE THREAD

**Issue by matskiv** [loft-sh/vcluster-generic-crd-sync-plugin#18]
There are some use cases where it is useful to have a label synced to the host cluster without a rewrite, and where this doesn't cause any conflicts. For example, ServiceMonitor (from Prometheus operator) uses labels to define which Prometheus instance is supposed to scrape it.
vcluster already has a flag which declares a list of label keys that will be copied to the physical resource without a rewrite as well:
https://github.com/loft-sh/vcluster/blob/aaef2d630aa4bbede5d962399ba876a69536acc3/cmd/vcluster/cmd/start.go#L137
This is not yet supported by the vcluster-generic-crd-sync-plugin, and we may discuss if it should be or not. But the best implementation of this feature request would probably be on a per-mapping level, e.g with a `syncLabels` field on the mapping:
```
version: v1beta1
mappings:
  - fromVirtualCluster:
      apiVersion: monitoring.coreos.com/v1
      kind: ServiceMonitor
      syncLabels:
        - "prometheus-instance"
```

P.S: while allowing arbitrary values for certain labels possesses a security risk in some cases, it might be deemed acceptable by the vcluster administrators. We just need to inform them wherever applicable.

**Comment by matskiv** [comment]
btw: I tried achieving the desired outcome via existing means, but the label key still got translated when I used this patch:
```
- op: copyFromObject
  fromPath: metadata.labels['prometheus-instance']
  path: metadata.labels['prometheus-instance']
 ```
However, this works, but doesn't fulfill the FR:
```
- op: add
  path: .metadata.labels
  value:
      release: prometheus
```
But I did not have time to investigate the difference in the code for these two^
