### ISSUE TITLE
Multiple syncback rules for the same Kind of Object leads to Indexer conflict error

### ISSUE THREAD

**Issue by neogopher** [loft-sh/vcluster-generic-crd-sync-plugin#26]
When we multiple rules for syncback for a certain kind of object under multiple top level Syncer mappings, it leads to Indexer conflict.

Please find example config below. Here syncback for secret leads to the indexer conflict error.
```yaml
version: v1beta1
mappings:
  - fromVirtualCluster:
      # CRD for the apiVersion+Kind is implicitly copied to the virtual cluster
      apiVersion: cert-manager.io/v1
      kind: Issuer
      patches:
        - op: rewriteName
          path: spec.ca.secretName
          sync:
            secret: true
      reversePatches:
        - op: copyFromObject
          fromPath: status
          path: status
  - fromVirtualCluster:
      # CRD for the apiVersion+Kind is implicitly copied to the virtual cluster
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      patches:
        - op: rewriteName
          path: metadata.annotations['cert-manager.io/issuer']
        - op: rewriteName
          path: spec.rules..http.paths..backend.service.name
        - op: rewriteName
          path: spec.tls..secretName
          sync:
            secret: true
      reversePatches:
        - op: copyFromObject
          fromPath: status
          path: status
      syncBack:
        - apiVersion: cert-manager.io/v1
          kind: Certificate
          selectors:
            - name:
                rewrittenPath: metadata.name
        - kind: Secret
          apiVersion: v1
          selectors:
            - name:
                rewrittenPath: spec.tls..secretName
  - fromVirtualCluster:
      apiVersion: cert-manager.io/v1
      kind: Certificate
      patches:
        - op: rewriteName
          path: spec.issuerRef.name
        - op: rewriteName
          path: spec.secretName
      reversePatches:
        - op: copyFromObject
          fromPath: status
          path: status
        - op: copyFromObject
          fromPath: spec.issuerRef.name
          path: metadata.annotations['test.loft.sh/issuerRefName']
        - op: rewriteName
          path: metadata.annotations['test.loft.sh/issuerRefName']
      syncBack:
        - kind: Secret
          apiVersion: v1
          selectors:
            - name:
                rewrittenPath: spec.secretName
          patches:
            - op: rewriteName
              path: metadata.annotations['cert-manager.io/certificate-name']
            - op: rewriteName
              path: metadata.annotations['cert-manager.io/issuer-name']
```

Devspace error logs:
```shell
root@vcluster-0:/vcluster# export CONFIG=$(cat hack/test-config.yaml) && go run -mod vendor main.go
I0929 12:44:36.083500    9482 logr.go:252] plugin: Try creating context...
I0929 12:44:36.103250    9482 main.go:36] Loading configuration:
version: v1beta1
mappings:
  - fromVirtualCluster:
      # CRD for the apiVersion+Kind is implicitly copied to the virtual cluster
      apiVersion: cert-manager.io/v1
      kind: Issuer
      patches:
        - op: rewriteName
          path: spec.ca.secretName
          sync:
            secret: true
      reversePatches:
        - op: copyFromObject
          fromPath: status
          path: status
  - fromVirtualCluster:
      # CRD for the apiVersion+Kind is implicitly copied to the virtual cluster
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      patches:
        - op: rewriteName
          path: metadata.annotations['cert-manager.io/issuer']
        - op: rewriteName
          path: spec.rules..http.paths..backend.service.name
        - op: rewriteName
          path: spec.tls..secretName
          sync:
            secret: true
      reversePatches:
        - op: copyFromObject
          fromPath: status
          path: status
      syncBack:
        - apiVersion: cert-manager.io/v1
          kind: Certificate
          selectors:
            - name:
                rewrittenPath: metadata.name
        - kind: Secret
          apiVersion: v1
          name: secret-from-ingress
          selectors:
            - name:
                rewrittenPath: spec.tls..secretName
  - fromVirtualCluster:
      apiVersion: cert-manager.io/v1
      kind: Certificate
      patches:
        - op: rewriteName
          path: spec.issuerRef.name
        - op: rewriteName
          path: spec.secretName
      reversePatches:
        - op: copyFromObject
          fromPath: status
          path: status
        - op: copyFromObject
          fromPath: spec.issuerRef.name
          path: metadata.annotations['test.loft.sh/issuerRefName']
        - op: rewriteName
          path: metadata.annotations['test.loft.sh/issuerRefName']
      syncBack:
        - kind: Secret
          apiVersion: v1
          selectors:
            - name:
                rewrittenPath: spec.secretName
          patches:
            - op: rewriteName
              path: metadata.annotations['cert-manager.io/certificate-name']
            - op: rewriteName
              path: metadata.annotations['cert-manager.io/issuer-name']
I0929 12:44:36.103760    9482 main.go:45] Loaded configuration:
version: v1beta1
mappings:
    - fromVirtualCluster:
        apiVersion: cert-manager.io/v1
        kind: Issuer
        patches:
            - op: rewriteName
              path: spec.ca.secretName
              sync:
                secret: true
        reversePatches:
            - op: copyFromObject
              fromPath: status
              path: status
    - fromVirtualCluster:
        apiVersion: networking.k8s.io/v1
        kind: Ingress
        patches:
            - op: rewriteName
              path: metadata.annotations['cert-manager.io/issuer']
            - op: rewriteName
              path: spec.rules..http.paths..backend.service.name
            - op: rewriteName
              path: spec.tls..secretName
              sync:
                secret: true
        reversePatches:
            - op: copyFromObject
              fromPath: status
              path: status
        syncBack:
            - apiVersion: cert-manager.io/v1
              kind: Certificate
              selectors:
                - name:
                    rewrittenPath: metadata.name
            - apiVersion: v1
              kind: Secret
              name: secret-from-ingress
              selectors:
                - name:
                    rewrittenPath: spec.tls..secretName
    - fromVirtualCluster:
        apiVersion: cert-manager.io/v1
        kind: Certificate
        patches:
            - op: rewriteName
              path: spec.issuerRef.name
            - op: rewriteName
              path: spec.secretName
        reversePatches:
            - op: copyFromObject
              fromPath: status
              path: status
            - op: copyFromObject
              fromPath: spec.issuerRef.name
              path: metadata.annotations['test.loft.sh/issuerRefName']
            - op: rewriteName
              path: metadata.annotations['test.loft.sh/issuerRefName']
        syncBack:
            - apiVersion: v1
              kind: Secret
              patches:
                - op: rewriteName
                  path: metadata.annotations['cert-manager.io/certificate-name']
                - op: rewriteName
                  path: metadata.annotations['cert-manager.io/issuer-name']
              selectors:
                - name:
                    rewrittenPath: spec.secretName
I0929 12:44:36.107734    9482 logr.go:252] plugin: Waiting for vcluster to become leader...
I0929 12:44:36.108334    9482 logr.go:252] plugin: Starting syncers...
F0929 12:44:36.108439    9482 main.go:150] Error starting plugin: register indices for Secret-back-syncer syncer: indexer conflict: map[field:indexbyvirtualname:{}]
exit status 255
root@vcluster-0:/vcluster# 
```
