### ISSUE TITLE
feature request: add selectors based on ownerReference for syncBack

### ISSUE THREAD

**Issue by matskiv** [loft-sh/vcluster-generic-crd-sync-plugin#27]
Implement support for the owner reference selector for the syncBack resources.

API proposal:
```
...
  syncBack:
     - kind: Secret
      apiVersion: v1
      selectors:
        - ownerReference:
            apiVersion: v1
            kind: Service
            name: # one of:
              value: specific-name
              rewrittenPath: metadata.name
```
We could also consider adding additional "utility" selectors that would not require writing out each field, e.g.:
`- vclusterOwnerReferece: {}` - same as ownerReference, but GVK + name that is set based on ownerReference that vcluster sets. By default it's a Service with vclusters name, but can be changed via flags AFAIK.
`- parentMappingOwnerReference{}` - same as ownerReference, but GVK is automatically set to parent mapping GVK and name is set to `rewrittenPath: metadata.name`
