### ISSUE TITLE
Feature request: Allow syncing select resources from the host cluster to the vcluster

### ISSUE THREAD

**Issue by ctrox** [loft-sh/vcluster-generic-crd-sync-plugin#45]
I'm using the crd sync plugin for cert-manager and enabled syncing of `Certificate` resources from the vcluster to the host. This works fine but as a user I have to know the names of the `ClusterIssuers` to reference in the `Certificate`.  It would be great if it were possible to sync those `ClusterIssuers` from the host cluster to the vcluster, similar to how the built-in ingress syncer will sync `IngressClasses` to the vcluster so the user knows which are available.

The field `fromHostCluster` already seems to exist within the config but AFAIK it's not being used anywhere in the code. I imagine a configuration would look like this:

```
mappings:
# this already works as expected
- fromVirtualCluster:
    apiVersion: cert-manager.io/v1
    kind: Certificate
    patches:
      - op: rewriteName
        path: spec.secretName
    reversePatches:
      - op: copyFromObject
        fromPath: status
        path: status
    syncBack:
      - kind: Secret
        apiVersion: v1
        selectors:
          - name:
              rewrittenPath: spec.secretName
        patches:
          - op: rewriteName
            path: metadata.annotations['cert-manager.io/certificate-name']
# this does not work yet!
- fromHostCluster:
    apiVersion: cert-manager.io/v1
    kind: ClusterIssuer
```

Slack thread for some more context: [https://loft-sh.slack.com/archives/C01N273CF4P/p1669970331139229](https://loft-sh.slack.com/archives/C01N273CF4P/p1669970331139229)
